### ISSUE TITLE
social media links in the footer don't work 

### ISSUE THREAD

**Issue by SahilKr24** [iot-lab-kiit/TheNatureFresh-web#4]
fix the social media links in the footer. Use [iotlab](https://iotkiit.in) footer links as reference and update the required files.

**Comment by Atimabh** [comment]
Hey! I would like to work on this @SahilKr24

**Comment by icoderharshit** [comment]
I would like to work upon this, @SahilKr24 ! Let me know if I can start working over it or assign me a similar kind of issue, I'm a first timer at contributing to Open-Source :)

**Comment by SahilKr24** [comment]
@Atimabh @icoderharshit you both can work upon this. If you wish to change the styles you can. Happy Hactoberfest. Godspeed.

**Comment by icoderharshit** [comment]
@SahilKr24 , please provie me with the links I should redirect this social media icons onclick, so that I can get this working asap.

**Comment by SahilKr24** [comment]
> @SahilKr24 , please provie me with the links I should redirect this social media icons onclick, so that I can get this working asap.

The links to social media handles can be found on the footer here [iotlabkiit](https://iotkiit.in/)
